#!/system/bin/sh

# HACK: patch simple2ext's script to prevent filesystem corruption
S2ECONFIG="/data/local/s2e_config/.mounts_ext4"
if [ -f $S2ECONFIG ];
then
    rm $S2ECONFIG
fi

# HACK: ensure supplicant uses standard Unix socket
#       needed for wpa_supplicant_ath (0.8.x)
WPACONFIG="/data/misc/wifi/wpa_supplicant.conf"
if [ $(cat $WPACONFIG | grep "ctrl_interface=wlan0") ]; then
    sed -e 's/ctrl_interface=wlan0/ctrl_interface=DIR=\/data\/system\/wpa_supplicant GROUP=wifi/g' -i $WPACONFIG
    chmod 0771 $WPACONFIG
    chown wifi:wifi $WPACONFIG
fi
