#!/system/bin/sh

# HACK: patch simple2ext's script to prevent filesystem corruption
S2ECONFIG="/data/local/s2e_config/.mounts_ext4"
if [ -f $S2ECONFIG ]; then
    rm $S2ECONFIG
fi

# HACK: transition any users of wpa_supplicant_ath (v8) back to
#       Android private socket config
WPACONFIG="/data/misc/wifi/wpa_supplicant.conf"
if [ -f $WPACONFIG ]; then
    if [ $(cat $WPACONFIG | grep "ctrl_interface=DIR") ]; then
        sed -e 's/ctrl_interface=DIR=\/data\/system\/wpa_supplicant GROUP=wifi/ctrl_interface=wlan0/g' -i $WPACONFIG
        chmod 0771 $WPACONFIG
        chown wifi:wifi $WPACONFIG
        rm -r /data/system/wpa_supplicant
    fi
fi

# Automatic ROM re-odexing
ODEXCONFIG="/data/local/.enableodex"
if [ -f $ODEXCONFIG ]; then
    reodexer check
fi
